
version: '3.3'

services:
  am-site:
    image: am-site
    restart: unless-stopped
    container_name: am-site
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      NGINX_SERVER_NAME: localhost
      VIRTUAL_HOST: kiosk.*
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    expose:
      - "80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      NGINX_SERVER_NAME: localhost
      VIRTUAL_HOST: blog.*

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
