version: 3.1

services:
  am-site:
    image: am-site
    restart: unless-stopped
    container_name: am-site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
  db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Sup3rTr1cky&H4rd.
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpressUser
       MYSQL_PASSWORD: W0rdPress1ng!

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       - "VIRTUAL_HOST=blog.domain.com"
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: W0rdPress1ng!
       WORDPRESS_DB_NAME: wordpress
  nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
